

export const Action = {

    GET_ORGANIZATIONS: 'GET_ORGANIZATIONS',

    UPDATE_ORG: "UPDATE_ORG",
    DELETE_ORG: "DELETE_ORG",

    CREATE_USER: "CREATE_USER",
    ADD_MEMBER: "ADD_MEMBER",
    REMOVE_MEMBER: "REMOVE_MEMBER",
    CHANGE_MEMBER_ROLE: 'CHANGE_MEMBER_ROLE',
    GET_MEMBERS_LIST: "GET_MEMBERS_LIST",

    GET_ALL_PROJECTS:"GET_ALL_PROJECTS",
    CREATE_PROJECT: "CREATE_PROJECT",
    VIEW_PROJECT:"VIEW_PROJECT",
    UPDATE_PROJECT_MEMBER_ROLE: 'UPDATE_PROJECT_MEMBER_ROLE',
    UPDATE_PROJECT: "UPDATE_PROJECT",
    ADD_PROJECT_MEMBER: "ADD_PROJECT_MEMBER",
    REMOVE_PROJECT_MEMBER: "REMOVE_PROJECT_MEMBER",
    DELETE_PROJECT: "DELETE_PROJECT",

    CREATE_TEAM: "CREATE_TEAM",
    DELETE_TEAM: "DELETE_TEAM",
    GET_TEAM_MEMBERS: "GET_TEAM_MEMBERS",
    ADD_TEAM_MEMBER: "ADD_TEAM_MEMBER",
    REMOVE_TEAM_MEMBER: "REMOVE_TEAM_MEMBER",

    CREATE_TASK: "CREATE_TASK",
    ASSIGN_TASK: "ASSIGN_TASK",
} as const

export type Action = typeof Action[keyof typeof Action]

